
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#ifndef __DPerson__H__
#define __DPerson__H__

#include <Base_DPerson.h>

namespace Device
{

class
    DPerson
    : public Base_DPerson
{

public:
    /* sample constructor */
    explicit DPerson (
        const Configuration::Person& config,
        Parent_DPerson* parent
    ) ;
    /* sample dtr */
    ~DPerson ();

    /* delegators for
    cachevariables and sourcevariables */


    /* delegators for methods */
    UaStatus callEat (
        OpcUa_Double amount
    ) ;

private:
    /* Delete copy constructor and assignment operator */
    DPerson( const DPerson& other );
    DPerson& operator=(const DPerson& other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

public:
    void update();

private:



};

}

#endif // __DPerson__H__
