
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.

    The stub of this file was generated by quasar (https://github.com/quasar-team/quasar/)

    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.


 */


#include <Configuration.hxx> // TODO; should go away, is already in Base class for ages

#include <DPerson.h>
#include <ASPerson.h>
#include <cmath>
namespace Device
{
// 1111111111111111111111111111111111111111111111111111111111111111111111111
// 1     GENERATED CODE STARTS HERE AND FINISHES AT SECTION 2              1
// 1     Users don't modify this code!!!!                                  1
// 1     If you modify this code you may start a fire or a flood somewhere,1
// 1     and some human being may possible cease to exist. You don't want  1
// 1     to be charged with that!                                          1
// 1111111111111111111111111111111111111111111111111111111111111111111111111






// 2222222222222222222222222222222222222222222222222222222222222222222222222
// 2     SEMI CUSTOM CODE STARTS HERE AND FINISHES AT SECTION 3            2
// 2     (code for which only stubs were generated automatically)          2
// 2     You should add the implementation but dont alter the headers      2
// 2     (apart from constructor, in which you should complete initializati2
// 2     on list)                                                          2
// 2222222222222222222222222222222222222222222222222222222222222222222222222

/* sample ctr */
DPerson::DPerson (
    const Configuration::Person& config,
    Parent_DPerson* parent
):
    Base_DPerson( config, parent)

    /* fill up constructor initialization list here */
{
    /* fill up constructor body here */
}

/* sample dtr */
DPerson::~DPerson ()
{
}

/* delegates for cachevariables */

/* Note: never directly call this function. */

UaStatus DPerson::writeActualHeight ( const OpcUa_Double& v)
{
    if(v<=0){
    	return OpcUa_BadInvalidArgument;
    }
    if(v>300){
    	return OpcUa_BadOutOfRange;
    }
	return OpcUa_Good;
}


/* delegators for methods */
UaStatus DPerson::callEat (
    OpcUa_Double amount
)
{
	if(amount<=0){
		return OpcUa_BadInvalidState;
	}

	OpcUa_Double weight;
	getAddressSpaceLink()->getActualWeight(weight);
	OpcUa_Double new_weight = weight + amount;
	getAddressSpaceLink()->setActualWeight(new_weight, OpcUa_Good);

    return OpcUa_Good;
}

UaStatus DPerson::callCalculateBMI (
    OpcUa_Double& BMI
)
{
	OpcUa_Double height;
	OpcUa_Double weight;
	getAddressSpaceLink()->getActualHeight(height);
	getAddressSpaceLink()->getActualWeight(weight);
    BMI = weight/ std::pow(height*std::pow(10, -2) , 2);
    getAddressSpaceLink()->setTheBMI(BMI,OpcUa_Good);
    return OpcUa_Good;
}

// 3333333333333333333333333333333333333333333333333333333333333333333333333
// 3     FULLY CUSTOM CODE STARTS HERE                                     3
// 3     Below you put bodies for custom methods defined for this class.   3
// 3     You can do whatever you want, but please be decent.               3
// 33333333333333333333333333333333eightSet(rand(),ua_good);33333333333333333333333333333333333333333
void DPerson::update(){
//	OpcUa_Double height;
//	getAddressSpaceLink()->getActualHeight(height);
//	OpcUa_Double weight;
//	getAddressSpaceLink()->getActualWeight(weight);
//	//weight+=addedWeight;
//	//getAddressSpaceLink()->setActualWeight(weight,OpcUa_Good);
//	//addedWeight = 0;
}
}
